### PR TITLE
Increment package version to 4.0.0

### PR DESCRIPTION
**Pull request by dianashk**

### CODE REVIEW

**Comment by dianashk** [comment]
```
$ npm publish
+ pelias-openstreetmap@4.0.0
```

**Comment by orangejulius** [comment]
PRs with version increments are kinda weird because what if I thumbs down this? you can't undo the publish :(

**Comment by orangejulius** [comment]
but, also :+1:

**Comment by dianashk** [comment]
yeah, I realized that after seeing the greenkeeper PR that was failing as soon as I moved this into the review column. Sorry. Let's discuss the right way to do the version increments.

**Pull request merged**
