### PR TITLE
Import multiple pbfs final

### LINKED ISSUE #55: Import multiple pbf files
originally reported by @loomsen in https://github.com/pelias/openstreetmap/issues/46

currently the `pelias/config` structure implies that a consumer can specify multiple `pbf` files to be imported; however the import script does not currently support this.

---

Thanks, all seems to be working fine now. However, I wonder if it's possible to import multiple pbf files?
I've tried adding another one into the json array file, but it doesn't seem to be imported. Only the first entry seems to be processed. If I import it afterwards, data from both show up, so this would work. Would be nicer to configure an array though.

```json
      "import": [{
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "germany-latest.osm.pbf"
      },
      {  
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "liechtenstein-latest.osm.pbf"
      }]
```

### PR DESCRIPTION
**Pull request by avulfson17**
Openstreetmap can now import multiple pbfs, when they are specified in the config. 

Supersedes https://github.com/pelias/openstreetmap/pull/156

Fixes #55

### CODE REVIEW

**Comment by orangejulius** [comment]
LGTM

**Comment by dianashk** [comment]
:shipit:

**Comment by orangejulius** [comment]
@avulfson17 if you rebase this on master to fix the conflicts, we can merge it!

**Comment by avulfson17** [comment]
what are the conflicts? what am i rebasing it to?

**Comment by orangejulius** [comment]
LGTM!

**Pull request merged**
